### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by rgreen1995** [rgreen1995/PTMCMCSampler#9]
Add tests of the code as part of the CI, I can think of simple tests such as. 

1. Check code actually runs of simple example
2. Check code returns correct parameters for simple example  (gaussian or linear regression ?)
3. Maybe check that each proposal does what we expect ? 

Probably many more, could check bilby tests?

This is closely related to #8

**Comment by hoyc1** [comment]
@rgreen1995, I plan on making multiple MRs for the different tests. Please do not close this issue until all tests are complete.

**Comment by rgreen1995** [comment]
Maybe should be another issue but could we add black to the CI so that the pep8 is fixed automatically ?

**Comment by rgreen1995** [comment]
finished with #32
